// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB12984f0DecodeMygoModel(in *jlexer.Lexer, out *GoodsImage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "image_id":
			out.ImageId = int64(in.Int64())
		case "url":
			out.Url = string(in.String())
		case "goods_id":
			out.GoodsId = int64(in.Int64())
		case "type":
			out.Type = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB12984f0EncodeMygoModel(out *jwriter.Writer, in GoodsImage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"image_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ImageId))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.Url))
	}
	{
		const prefix string = ",\"goods_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.GoodsId))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GoodsImage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB12984f0EncodeMygoModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GoodsImage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB12984f0EncodeMygoModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GoodsImage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB12984f0DecodeMygoModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GoodsImage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB12984f0DecodeMygoModel(l, v)
}
func easyjsonB12984f0DecodeMygoModel1(in *jlexer.Lexer, out *Goods) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "goods_id":
			out.GoodsId = int64(in.Int64())
		case "goods_name":
			out.GoodsName = string(in.String())
		case "goods_price":
			out.GoodsPrice = float64(in.Float64())
		case "goods_weight":
			out.GoodsWeight = float64(in.Float64())
		case "image":
			if in.IsNull() {
				in.Skip()
				out.Image = nil
			} else {
				in.Delim('[')
				if out.Image == nil {
					if !in.IsDelim(']') {
						out.Image = make([]GoodsImage, 0, 1)
					} else {
						out.Image = []GoodsImage{}
					}
				} else {
					out.Image = (out.Image)[:0]
				}
				for !in.IsDelim(']') {
					var v1 GoodsImage
					(v1).UnmarshalEasyJSON(in)
					out.Image = append(out.Image, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB12984f0EncodeMygoModel1(out *jwriter.Writer, in Goods) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"goods_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.GoodsId))
	}
	{
		const prefix string = ",\"goods_name\":"
		out.RawString(prefix)
		out.String(string(in.GoodsName))
	}
	{
		const prefix string = ",\"goods_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.GoodsPrice))
	}
	{
		const prefix string = ",\"goods_weight\":"
		out.RawString(prefix)
		out.Float64(float64(in.GoodsWeight))
	}
	{
		const prefix string = ",\"image\":"
		out.RawString(prefix)
		if in.Image == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Image {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Goods) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB12984f0EncodeMygoModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Goods) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB12984f0EncodeMygoModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Goods) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB12984f0DecodeMygoModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Goods) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB12984f0DecodeMygoModel1(l, v)
}
