package common

const Order = `{
	"es_order":{
		"properties":{
			"order_id":{"type":"keyword"},
			"user_id":{"type":"keyword"},
			"goods":{
				"type":"nested",
				"properties":{
					"goods_id":{"type":"keyword"},
					"goods_num":{"type":"integer"},
					"goods_price":{"type":"double"},
					"goods_total_price":{"type":"double"},
					"goods_weight":{"type":"double"}
				}
			},
			"total_num":{"type":"double"},
			"total_weight":{"type":"double"},
			"total_price":{"type":"double"}
		}
	}
}
`

const User = `{
	"es_user":{
		"properties":{
			"user_id":{"type":"keyword"},
			"nickname":{"type":"text"},
			"name":{"type":"text"},
			"open_id":{"type":"keyword"},
			"address":{
				"type":"nested",
				"properties":{
					"address_id":{"type":"keyword"},
					"province":{"type":"keyword"},
					"city":{"type":"keyword"},
					"district":{"type":"keyword"},
					"detail":{"type":"text"},
					"mobile":{"type":"integer"},
					"name":{"type":"keyword"}
				}
			},
			"avatarUrl":{"type":"keyword"},
			"city":{"type":"keyword"},
			"country":{"type":"keyword"},
			"province":{"type":"keyword"},
			"language":{"type":"keyword"},
			"gender":{"type":"integer"}
		}
	}
}`

const Address = `{
	"es_address":{
		"properties":{
			"user_id":{"type":"keyword"},
			"address_id":{"type":"text"},
			"status":{"type":"integer"},
			"province":{"type":"keyword"},
			"city":{"type":"keyword"},
			"district":{"type":"keyword"},
			"detail":{"type":"text"},
			"mobile":{"type":"long"},
			"name":{"type":"keyword"}
		}
	}
}`

const Goods = `{
	"es_goods":{
		"properties":{
			"goods_id":{"type":"long"},
			"goods_name":{"type":"text"},
			"images":{
				"type":"nested",
				"properties":{
					"image_id":{"type":"keyword"},
					"url":{"type":"keyword"},
					"status":{"type":"integer"},
					"type":{"type":"integer"}
				}
			},
			"content":{"type":"text"},
			"status":{"type":"integer"},
			"is_new":{"type":"integer"},
			"is_hot":{"type":"integer"},
			"goods_price":{"type":"double"},
			"goods_weight":{"type":"double"},
			"category_id":{"type":"keyword"}
		}
	}
}`

const Category = `{
	"es_category":{
		"properties":{
			"category_id":{"type":"keyword"},
			"category_name":{"type":"text"},
			"image":{"type":"keyword"},
			"child_category":{
				"type":"nested",
				"properties":{
					"category_id":{"type":"keyword"},
					"category_name":{"type":"text"},
					"image":{"type":"keyword"}
				}
			},
			"status":{"type":"integer"}
		}
	}
}`

const Cart = `{
	"es_cart":{
		"properties":{
			"cart_id":{"type":"keyword"},
			"user_id":{"type":"keyword"},
			"type":{"type":"integer"},
			"goods":{
				"type":"nested",
				"properties":{
					"goods_id":{"type":"keyword"},
					"goods_name":{"type":"text"},
					"images":{"type":"keyword"},
					"goods_price":{"type":"double"},
					"goods_weight":{"type":"double"},
					"category_id":{"type":"keyword"},
					"total_num":{"type":"double"},
					"total_weight":{"type":"double"},
					"total_price":{"type":"double"}
				}
			},
			"status":{"type":"integer"},
			"total_num":{"type":"double"},
			"total_weight":{"type":"double"},
			"total_price":{"type":"double"},
			"created_at":{"type":"keyword"}
		}
	}
}`
